package io.github.fherbreteau.matrix.model;

import io.github.fherbreteau.matrix.json.JsonObject;
import io.github.fherbreteau.matrix.json.JsonValue;

/**
 * A plain-text or formatted message body for the {@code m.room.message} event. Unknown message
 * fields can be added through the raw content. Use the {@link Builder} via {@link #builder()}.
 *
 * @see <a href="https://spec.matrix.org/latest/client-server-api/m-room-message-msgtypes">Matrix
 *     specification</a>
 */
public final class MessageBody {

  private final String msgtype;
  private final String body;
  private final String formattedBody;
  private final String format;

  private MessageBody(Builder builder) {
    this.msgtype = builder.msgtype;
    this.body = builder.body;
    this.formattedBody = builder.formattedBody;
    this.format = builder.format;
  }

  /**
   * Returns a plain-text message of type {@code m.text}.
   *
   * @param text the plain-text body
   * @return a text message
   */
  public static MessageBody text(String text) {
    return builder().msgtype("m.text").body(text).build();
  }

  /**
   * Returns a notice message of type {@code m.notice}, typically generated by bots and expected not
   * to trigger user notifications.
   *
   * @param text the plain-text body
   * @return a notice message
   */
  public static MessageBody notice(String text) {
    return builder().msgtype("m.notice").body(text).build();
  }

  /**
   * Returns a new {@link Builder}.
   *
   * @return a new builder
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Serializes the message as the content of an {@code m.room.message} event, omitting unset
   * fields.
   *
   * @return the event content
   */
  public JsonValue toJson() {
    JsonObject content = new JsonObject().put("msgtype", msgtype).put("body", body);
    if (formattedBody != null) {
      content.put("formatted_body", formattedBody);
    }
    if (format != null) {
      content.put("format", format);
    }
    return content;
  }

  /** Builder for {@link MessageBody}. */
  public static final class Builder {

    private String msgtype = "m.text";
    private String body;
    private String formattedBody;
    private String format;

    private Builder() {}

    /**
     * Sets the message type: {@code m.text}, {@code m.notice}, {@code m.emote} or a custom type.
     *
     * @param msgtype the message type
     * @return this builder for chaining
     */
    public Builder msgtype(String msgtype) {
      this.msgtype = msgtype;
      return this;
    }

    /**
     * Sets the plain-text fallback body, required by the spec.
     *
     * @param body the plain-text body
     * @return this builder for chaining
     */
    public Builder body(String body) {
      this.body = body;
      return this;
    }

    /**
     * Sets the formatted version of the body, such as HTML.
     *
     * @param formattedBody the formatted body
     * @return this builder for chaining
     */
    public Builder formattedBody(String formattedBody) {
      this.formattedBody = formattedBody;
      return this;
    }

    /**
     * Sets the formatting algorithm of the formatted body, typically {@code
     * org.matrix.custom.html}.
     *
     * @param format the formatting algorithm
     * @return this builder for chaining
     */
    public Builder format(String format) {
      this.format = format;
      return this;
    }

    /**
     * Builds the message body.
     *
     * @return the message body
     */
    public MessageBody build() {
      if (body == null || body.isBlank()) {
        throw new IllegalArgumentException("body is required");
      }
      return new MessageBody(this);
    }
  }
}
