package io.github.fherbreteau.matrix.endpoint;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

import io.github.fherbreteau.matrix.error.MatrixServerException;
import io.github.fherbreteau.matrix.json.JsonParser;
import io.github.fherbreteau.matrix.model.EventId;
import io.github.fherbreteau.matrix.model.FileTransactionIdStore;
import io.github.fherbreteau.matrix.model.PasswordCredentials;
import io.github.fherbreteau.matrix.model.RoomId;
import io.github.fherbreteau.matrix.transport.HttpTransport.Request;
import io.github.fherbreteau.matrix.transport.HttpTransport.Response;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class TransactionIdClientTest {

  private static final String LOGIN_OK =
      "{\"user_id\":\"@alice:matrix.org\",\"access_token\":\"secret-token\",\"device_id\":\"DEV\"}";
  private static final String EVENT_OK = "{\"event_id\":\"$event:matrix.org\"}";

  @TempDir Path tempDir;

  @Test
  void keyedSendReusesTransactionIdWhenRequestFails() {
    var requests = new ArrayList<Request>();
    var store = new FileTransactionIdStore(tempDir.resolve("transactions.json"));
    MatrixClient client =
        client(
            store,
            requests,
            new Response(200, LOGIN_OK),
            new Response(500, "{\"errcode\":\"M_UNKNOWN\",\"error\":\"retry\"}"),
            new Response(200, EVENT_OK));
    client.login(new PasswordCredentials("@alice:matrix.org", "secret"));
    var roomId = RoomId.of("!room:matrix.org");
    var content = JsonParser.parse("{\"body\":\"hello\"}");

    assertThatExceptionOfType(MatrixServerException.class)
        .isThrownBy(
            () -> client.sendMessageEventWithKey(roomId, "m.room.message", content, "op-1"));
    String firstTransaction = transactionId(requests.get(1).url());
    EventId eventId = client.sendMessageEventWithKey(roomId, "m.room.message", content, "op-1");
    String retryTransaction = transactionId(requests.get(2).url());

    assertThat(eventId.value()).isEqualTo("$event:matrix.org");
    assertThat(retryTransaction).isEqualTo(firstTransaction);
    assertThat(store.find("op-1")).isEmpty();
  }

  @Test
  void defaultTransactionStorePreservesCurrentAutoGeneratedSendBehavior() {
    var requests = new ArrayList<Request>();
    MatrixClient client =
        client(
            new FileTransactionIdStore(tempDir.resolve("default-store.json")),
            requests,
            new Response(200, LOGIN_OK),
            new Response(200, EVENT_OK));
    client.login(new PasswordCredentials("@alice:matrix.org", "secret"));
    assertThat(
            client.sendMessageEventWithTransactionId(
                RoomId.of("!room:matrix.org"),
                "m.room.message",
                JsonParser.parse("{}"),
                "caller-provided-id"))
        .extracting(EventId::value)
        .isEqualTo("$event:matrix.org");
    assertThat(transactionId(requests.getLast().url())).isNotBlank();
  }

  @Test
  void keyedSendGetsNewIdAfterSuccessfulCompletion() {
    var requests = new ArrayList<Request>();
    var store = new FileTransactionIdStore(tempDir.resolve("transactions-success.json"));
    MatrixClient client =
        client(
            store,
            requests,
            new Response(200, LOGIN_OK),
            new Response(200, EVENT_OK),
            new Response(200, EVENT_OK));
    client.login(new PasswordCredentials("@alice:matrix.org", "secret"));
    var content = JsonParser.parse("{\"body\":\"hello\"}");
    client.sendMessageEventWithKey(
        RoomId.of("!room:matrix.org"), "m.room.message", content, "op-1");
    client.sendMessageEventWithKey(
        RoomId.of("!room:matrix.org"), "m.room.message", content, "op-1");
    assertThat(transactionId(requests.get(1).url()))
        .isNotEqualTo(transactionId(requests.get(2).url()));
  }

  @Test
  void redactionRetriesReusePersistedTransactionId() {
    var requests = new ArrayList<Request>();
    var store = new FileTransactionIdStore(tempDir.resolve("redactions.json"));
    MatrixClient client =
        client(
            store,
            requests,
            new Response(200, LOGIN_OK),
            new Response(500, "{\"errcode\":\"M_UNKNOWN\",\"error\":\"retry\"}"),
            new Response(200, EVENT_OK));
    client.login(new PasswordCredentials("@alice:matrix.org", "secret"));
    var roomId = RoomId.of("!room:matrix.org");
    var eventId = EventId.of("$event:matrix.org");
    assertThatExceptionOfType(MatrixServerException.class)
        .isThrownBy(() -> client.redact(roomId, eventId, "reason"));
    String firstTransaction = transactionId(requests.get(1).url());
    client.redact(roomId, eventId, "reason");
    assertThat(transactionId(requests.get(2).url())).isEqualTo(firstTransaction);
    assertThat(store.find("redact\n!room:matrix.org\n$event:matrix.org")).isEmpty();
  }

  private MatrixClient client(
      FileTransactionIdStore store, List<Request> requests, Response... responses) {
    var transport = new HttpTransportStub();
    for (Response response : responses) {
      transport.enqueue(response);
    }
    transport.recordInto(requests);
    return MatrixClient.builder("https://matrix.example.org")
        .transport(transport)
        .transactionIdStore(store)
        .build();
  }

  private static String transactionId(String url) {
    return url.substring(url.lastIndexOf('/') + 1);
  }
}
